/* Automatically generated by configure - do not modify */
#ifndef CONFIG_NOOCDIR
# define CONFIG_NOOCDIR "/usr/local/lib/nooc"
#endif
#ifndef CONFIG_NOOC_PREDEFS
# define CONFIG_NOOC_PREDEFS 1
#endif
#define NOOC_VERSION "0.0.1"
#define GCC_MAJOR 0
#define GCC_MINOR 1
#define CC_NAME CC_nooc
